# file to create and maintain an index.html file which will contain a table of datasets for easy maintainance
import glob
import json
import os
import requests
import datetime


template_header = '''
<html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">
<title>CLUTRR Dataset List</title>
<link rel="stylesheet" href="style.css">
<style>
			body {
				box-sizing: border-box;
				min-width: 200px;
				max-width: 980px;
				margin: 0 auto;
				padding: 45px;
			}
		</style>
</head>
<body>
<article class="markdown-body">
<h1><a id="user-content-github-markdown-css-demo" class="anchor" href="#github-markdown-css-demo" aria-hidden="true"><span class="octicon octicon-link"></span></a>CLUTRR v2.0 Dataset List</h1>
<p><a name="user-content-headers"></a></p><a name="user-content-headers">
</a>
<p>Contains the list of datasets and their generation configuration.</p>

<table><thead>
<tr>
<th>Name</th>
<th align="center">Training</th>
<th aligh="right">Number of Training rows</th>
<th align="right">Testing</th>
<th align="right">Number of Testing rows</th>
<th align="right">Time created</th>
</tr>
</thead><tbody>
'''

template_footer = '''
</tbody></table>
<p>For questions, contact Koustuv Sinha.</p>
</article>
</body></html>
'''

CSS_TEMPLATE = 'https://sindresorhus.com/github-markdown-css/github-markdown.css'

def generate_webpage(data_path):
    """
    Reads the list of directories, reads their config file, and generates a Github flavored webpage
    <tr>
<td></td>
<td></td>
<td></td>
</tr>
    :return:
    """
    folders = glob.glob(os.path.join(data_path, '*', ''))
    print("Found {} folders.".format(len(folders)))
    web_page = template_header
    generated_at = '<p>This webpage is autogenerated at {}</p>'.format(datetime.datetime.now().strftime("%Y-%m-%d %H:%M"))
    for folder in folders:
        print('Reading {}'.format(folder))
        config = json.load(open(os.path.join(folder, 'config.json')))
        train_task = config['train_task'].keys()
        test_tasks = config['test_tasks'].keys()
        train_rows = sum([config['args'][config['train_task'][tr]]['num_rows'] for tr in train_task])
        test_rows = sum([config[config['test_tasks'][tr]]['num_rows'] for tr in test_tasks])
        name = folder.split('/')[-2]
        name_url = '<a href={}>{}</a>'.format(name + '.zip', name)
        gen_time = datetime.datetime.fromtimestamp(os.stat(folder).st_mtime).strftime("%y-%m-%d / %H:%M")
        row_web = '<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>'.format(name_url, ','.join(train_task), train_rows, ','.join(test_tasks), test_rows, gen_time)
        web_page += row_web
    web_page += generated_at
    web_page += template_footer
    css = requests.get(CSS_TEMPLATE).text
    with open(os.path.join(data_path, 'style.css'), 'w') as fp:
        fp.write(css)
    with open(os.path.join(data_path, 'index.html'), 'w') as fp:
        fp.write(web_page)

if __name__ == '__main__':
    generate_webpage('/home/ml/ksinha4/mlp/clutrr/data')

